[project]
name = "fm-extraction"
version = "0.1.0"
requires-python = ">=3.8"
dependencies = [
    "pandas",
    "numpy",
    "scipy",
    "SimpleITK",
    "foundation-cancer-image-biomarker",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
prerelease = "allow"
